config/routes.rb
IdeaNotebook::Application.routes.draw do

  # Create
  get "/ideas/new", { :controller => 'ideas', :action => 'new', :as => 'new_idea' }
  post "/ideas", { :controller => 'ideas', :action => 'create', :as => 'ideas' }

  # Read
  get "/ideas", { :controller => 'ideas', :action => 'index' }
  get "/ideas/:id", { :controller => 'ideas', :action => 'show', :as => 'idea' }

  # Update
  get "/ideas/:id/edit", { :controller => 'ideas', :action => 'edit', :as => 'edit_idea'}
  patch "/ideas/:id", { :controller => 'ideas', :action => 'update' }

  # Destroy
  delete "/ideas/:id", { :controller => 'ideas', :action => 'destroy' }

end

app/models/idea.rb
class Idea < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  def index
    @ideas = Idea.all
    respond_to do |format|
      format.html { render 'index' } #doesn't have to have the render
      format.json { render json: @ideas}
    end
  end

  def new
    @idea = Idea.new
    respond_to do |format|
      format.html { render 'new' }
    end
  end

  def create
    Idea.create(idea_params)

    respond_to do |format|
      format.html { redirect_to ideas_url }
    end
  end

  def show
    @idea = Idea.find_by_id(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @idea }
    end
  end

  def edit
    @idea = Idea.find_by_id(params[:id])

    respond_to do |format|
      format.html
    end
  end

  def update
    @idea = Idea.find_by_id(params[:id])
    @idea.update(idea_params)

    respond_to do |format|
      format.html { redirect_to idea_url(@idea.id) }
    end
  end

  def destroy
    idea = Idea.find_by_id(params[:id])
    idea.destroy

    respond_to do |format|
      format.html { redirect_to ideas_url }
    end
  end

  private

  def idea_params
    params.require(:idea).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :description %>
    <%= f.text_field :description %>

    <%= f.submit %>
<% end %>

app/views/ideas/edit.html.erb
<h1>Edit idea #<%= @idea.id %></h1>

<%= render 'form' %>

app/views/ideas/index.html.erb
<h1>Idea Notebook</h1>

<%= link_to "Add a new idea", new_idea_path  %>

<ul>
<% @ideas.each do |idea| %>
  <li>
    <%= idea.name %>: <%= idea.description %>
    <%= link_to "Show", idea_path(idea.id)  %>
    <%= link_to "Edit", edit_idea_path(idea.id)  %>
    <%= link_to "Destroy", idea_path(idea.id), :method => "delete", :data => { :confirm => "Are you sure?" }  %>
  </li>
<% end %>
</ul>

app/views/ideas/new.html.erb
<h1>Enter a new idea</h1>

<%= render 'form' %>

app/views/ideas/show.html.erb
<h1>Idea #<%= @idea.id %></h1>

<h2><%= @idea.name %>: <%= @idea.description %></h2>

<%= link_to "Back to list of ideas", ideas_path  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IdeaNotebook</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>